version: '3.7'

services:

    db:
        restart: always
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - .env
        ports:
            - '5434:5432'


volumes:
    postgres_data:
