version: '3.7'

services:

    db:
        restart: always
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - .env

    web:
        build: .
        ports:
            - '8080:8080'
        volumes:
            - ./app:/app
        env_file: .env
        depends_on:
            - db
        command: python app.py


volumes:
    postgres_data:
